// // Full-screen vertical video reels data for Instagram/YouTube-style Reels UI.

// export const blogsData = [
//   {
//     id: 1,
//     title: "The Soul Behind The Seam",
//     description: "Meet the founders and the vision of SoulSeam. Dive into our creative journey.",
//     videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
//     thumbnail: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=720&q=80",
//     category: "Story",
//     duration: "2:05",
//   },
//   {
//     id: 2,
//     title: "Streetwear Launch Vlog",
//     description: "Follow our team on launch day. Real moments, real fashion.",
//     videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
//     thumbnail: "https://images.unsplash.com/photo-1519125323398-675f0ddb6308?auto=format&fit=crop&w=720&q=80",
//     category: "Vlog",
//     duration: "4:12",
//   },
//   {
//     id: 3,
//     title: "Sustainable Fabric 101",
//     description: "How we choose sustainable fabrics for every piece. Quick explainer.",
//     videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4",
//     thumbnail: "https://images.unsplash.com/photo-1465101046530-73398c7f28ca?auto=format&fit=crop&w=720&q=80",
//     category: "Explainer",
//     duration: "1:54",
//   },
//   {
//     id: 4,
//     title: "Day in the Studio",
//     description: "A behind-the-scenes look at our creative process. No filters, just flow.",
//     videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4",
//     thumbnail: "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=720&q=80",
//     category: "Vlog",
//     duration: "3:08",
//   },
//   {
//     id: 5,
//     title: "Soulful Threads - Fall Drop",
//     description: "Showcasing this season’s collection in style. Modern vibes, cool edits.",
//     videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
//     thumbnail: "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?auto=format&fit=crop&w=720&q=80",
//     category: "Story",
//     duration: "2:41",
//   },
//   {
//     id: 6,
//     title: "Trend Breakdown: Oversized Tees",
//     description: "Why oversized is timeless. Styling tips for the bold.",
//     videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
//     thumbnail: "https://images.unsplash.com/photo-1515378791036-0648a3ef77b2?auto=format&fit=crop&w=720&q=80",
//     category: "Explainer",
//     duration: "1:19",
//   },
//   {
//     id: 7,
//     title: "Fashion For Good",
//     description: "How every SoulSeam purchase gives back. A feel-good explainer.",
//     videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
//     thumbnail: "https://images.unsplash.com/photo-1454023492550-5696f8ff10e1?auto=format&fit=crop&w=720&q=80",
//     category: "Explainer",
//     duration: "2:27",
//   },
//   {
//     id: 8,
//     title: "Seamless Urban Styles",
//     description: "Blending comfort and cool. See our favorite city looks.",
//     videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4",
//     thumbnail: "https://images.unsplash.com/photo-1518684079-41e65393b87b?auto=format&fit=crop&w=720&q=80",
//     category: "Story",
//     duration: "1:44",
//   },
//   {
//     id: 9,
//     title: "Community: You Wear The Story",
//     description: "SoulSeam fam showing off their style. Tag us to get featured!",
//     videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4",
//     thumbnail: "https://images.unsplash.com/photo-1503676382389-4809596d5290?auto=format&fit=crop&w=720&q=80",
//     category: "Vlog",
//     duration: "3:33",
//   },
//   {
//     id: 10,
//     title: "Zero Waste Packing Explained",
//     description: "Inside our eco-friendly packaging—good for you, better for Earth.",
//     videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/VolkswagenGTIReview.mp4",
//     thumbnail: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&w=720&q=80",
//     category: "Explainer",
//     duration: "1:58",
//   },
//   {
//     id: 11,
//     title: "SoulSeam Pop-Up Recap",
//     description: "Relive the best moments from our latest pop-up event.",
//     videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4",
//     thumbnail: "https://images.unsplash.com/photo-1444065381814-865dc9da92c0?auto=format&fit=crop&w=720&q=80",
//     category: "Vlog",
//     duration: "2:29",
//   },
//   {
//     id: 12,
//     title: "Wear The Change",
//     description: "Fashion with a conscience—see how your fit can make a difference.",
//     videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4",
//     thumbnail: "https://images.unsplash.com/photo-1465101178521-c1a9136a3be5?auto=format&fit=crop&w=720&q=80",
//     category: "Story",
//     duration: "2:11",
//   }
// ];
